<?php
  if ($_COOKIE["Language"] == "FR") {
    $create  = "NOUVELLE PARTIE";
    $join    = "REJOINDRE UNE PARTIE";
    $ol      = "EN";
    $approve = "VOUS ALLEZ VOUS DEMATERIALISER ET ENTRER DANS L'ORDINATEUR. ETES VOUS CERTAIN?";
    $enter   = "OUI";
  } else {
    $create  = "NEW GAME";
    $join    = "JOIN GAME";
    $ol      = "FR";
    $approve = "YOU ARE ABOUT TO BE DEMATERIALIZED AND ENTER THE GRID. DO YOU WISH TO PROCEED?";
    $enter   = "YES";
  }

  // DATABASE CONNECTION
	$servername = "localhost";
	$username   = "webserver";
	$password   = "BP4Life";
	$database   = "tron";

  $conn = mysqli_connect($servername, $username, $password, $database);
  $host = "false";
  if ($conn) {
    if (empty($_POST["GameID"])) {
      $id = "";
      do {
        $alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        $id = "";
        for ($i = 0; $i < 4; $i++) {
            $id .= $alphabet[rand(0, 25)];
        }

        $sql = "INSERT INTO tron (GameID) VALUES ('" . $id . "')";
      } while (!$conn->query($sql));
      $host = "true";
    } else {
      $id = strtoupper($_POST["GameID"]);
      $sql = "SELECT GameID FROM tron WHERE GameID='" . $id . "'";
      if (!$conn->query($sql)->num_rows) {
        header("Location: /tron");
      }
    }
    $conn->close();
  } else {
    header("Location: /tron");
  }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>TRON</title>
    <link rel="stylesheet" type="text/css" href="/css/tron.css"/>
    <script src="/js/tron.js" type="text/javascript"></script>
    <script>
      _GAME_ID = "<?php echo($id); ?>";
      wakeupServer();
    </script>
  </head>
  <body onload="drawGrid()" onresize="drawGrid()" onkeydown="changeDirection(event)">
    <div id="Title">TRON</div>
    <div id="GameID"><?php echo($id); ?></div>
    <div id="Lines">
    </div>
    <div id="BoardContainer">
      <div id="Board">
        <div id="T0L0" class="cell" style="" color=""></div>
        <div id="T0L1" class="cell" style="" color=""></div>
        <div id="T0L2" class="cell" style="" color=""></div>
        <div id="T0L3" class="cell" style="" color=""></div>
        <div id="T0L4" class="cell" style="" color=""></div>
        <div id="T0L5" class="cell" style="" color=""></div>
        <div id="T0L6" class="cell" style="" color=""></div>
        <div id="T0L7" class="cell" style="" color=""></div>
        <div id="T0L8" class="cell" style="" color=""></div>
        <div id="T0L9" class="cell" style="" color=""></div>
        <div id="T0L10" class="cell" style="" color=""></div>
        <div id="T0L11" class="cell" style="" color=""></div>
        <div id="T0L12" class="cell" style="" color=""></div>
        <div id="T0L13" class="cell" style="" color=""></div>
        <div id="T0L14" class="cell" style="" color=""></div>
        <div id="T0L15" class="cell" style="" color=""></div>
        <div id="T0L16" class="cell" style="" color=""></div>
        <div id="T0L17" class="cell" style="" color=""></div>
        <div id="T0L18" class="cell" style="" color=""></div>
        <div id="T0L19" class="cell" style="" color=""></div>
        <div id="T0L20" class="cell" style="" color=""></div>
        <div id="T0L21" class="cell" style="" color=""></div>
        <div id="T0L22" class="cell" style="" color=""></div>
        <div id="T0L23" class="cell" style="" color=""></div>
        <div id="T0L24" class="cell" style="" color=""></div>
        <div id="T0L25" class="cell" style="" color=""></div>
        <div id="T0L26" class="cell" style="" color=""></div>
        <div id="T0L27" class="cell" style="" color=""></div>
        <div id="T0L28" class="cell" style="" color=""></div>
        <div id="T0L29" class="cell" style="" color=""></div>
        <div id="T0L30" class="cell" style="" color=""></div>
        <div id="T0L31" class="cell" style="" color=""></div>
        <div id="T1L0" class="cell" style="" color=""></div>
        <div id="T1L1" class="cell" style="" color=""></div>
        <div id="T1L2" class="cell" style="" color=""></div>
        <div id="T1L3" class="cell" style="" color=""></div>
        <div id="T1L4" class="cell" style="" color=""></div>
        <div id="T1L5" class="cell" style="" color=""></div>
        <div id="T1L6" class="cell" style="" color=""></div>
        <div id="T1L7" class="cell" style="" color=""></div>
        <div id="T1L8" class="cell" style="" color=""></div>
        <div id="T1L9" class="cell" style="" color=""></div>
        <div id="T1L10" class="cell" style="" color=""></div>
        <div id="T1L11" class="cell" style="" color=""></div>
        <div id="T1L12" class="cell" style="" color=""></div>
        <div id="T1L13" class="cell" style="" color=""></div>
        <div id="T1L14" class="cell" style="" color=""></div>
        <div id="T1L15" class="cell" style="" color=""></div>
        <div id="T1L16" class="cell" style="" color=""></div>
        <div id="T1L17" class="cell" style="" color=""></div>
        <div id="T1L18" class="cell" style="" color=""></div>
        <div id="T1L19" class="cell" style="" color=""></div>
        <div id="T1L20" class="cell" style="" color=""></div>
        <div id="T1L21" class="cell" style="" color=""></div>
        <div id="T1L22" class="cell" style="" color=""></div>
        <div id="T1L23" class="cell" style="" color=""></div>
        <div id="T1L24" class="cell" style="" color=""></div>
        <div id="T1L25" class="cell" style="" color=""></div>
        <div id="T1L26" class="cell" style="" color=""></div>
        <div id="T1L27" class="cell" style="" color=""></div>
        <div id="T1L28" class="cell" style="" color=""></div>
        <div id="T1L29" class="cell" style="" color=""></div>
        <div id="T1L30" class="cell" style="" color=""></div>
        <div id="T1L31" class="cell" style="" color=""></div>
        <div id="T2L0" class="cell" style="" color=""></div>
        <div id="T2L1" class="cell" style="" color=""></div>
        <div id="T2L2" class="cell" style="" color=""></div>
        <div id="T2L3" class="cell" style="" color=""></div>
        <div id="T2L4" class="cell" style="" color=""></div>
        <div id="T2L5" class="cell" style="" color=""></div>
        <div id="T2L6" class="cell" style="" color=""></div>
        <div id="T2L7" class="cell" style="" color=""></div>
        <div id="T2L8" class="cell" style="" color=""></div>
        <div id="T2L9" class="cell" style="" color=""></div>
        <div id="T2L10" class="cell" style="" color=""></div>
        <div id="T2L11" class="cell" style="" color=""></div>
        <div id="T2L12" class="cell" style="" color=""></div>
        <div id="T2L13" class="cell" style="" color=""></div>
        <div id="T2L14" class="cell" style="" color=""></div>
        <div id="T2L15" class="cell" style="" color=""></div>
        <div id="T2L16" class="cell" style="" color=""></div>
        <div id="T2L17" class="cell" style="" color=""></div>
        <div id="T2L18" class="cell" style="" color=""></div>
        <div id="T2L19" class="cell" style="" color=""></div>
        <div id="T2L20" class="cell" style="" color=""></div>
        <div id="T2L21" class="cell" style="" color=""></div>
        <div id="T2L22" class="cell" style="" color=""></div>
        <div id="T2L23" class="cell" style="" color=""></div>
        <div id="T2L24" class="cell" style="" color=""></div>
        <div id="T2L25" class="cell" style="" color=""></div>
        <div id="T2L26" class="cell" style="" color=""></div>
        <div id="T2L27" class="cell" style="" color=""></div>
        <div id="T2L28" class="cell" style="" color=""></div>
        <div id="T2L29" class="cell" style="" color=""></div>
        <div id="T2L30" class="cell" style="" color=""></div>
        <div id="T2L31" class="cell" style="" color=""></div>
        <div id="T3L0" class="cell" style="" color=""></div>
        <div id="T3L1" class="cell" style="" color=""></div>
        <div id="T3L2" class="cell" style="" color=""></div>
        <div id="T3L3" class="cell" style="" color=""></div>
        <div id="T3L4" class="cell" style="" color=""></div>
        <div id="T3L5" class="cell" style="" color=""></div>
        <div id="T3L6" class="cell" style="" color=""></div>
        <div id="T3L7" class="cell" style="" color=""></div>
        <div id="T3L8" class="cell" style="" color=""></div>
        <div id="T3L9" class="cell" style="" color=""></div>
        <div id="T3L10" class="cell" style="" color=""></div>
        <div id="T3L11" class="cell" style="" color=""></div>
        <div id="T3L12" class="cell" style="" color=""></div>
        <div id="T3L13" class="cell" style="" color=""></div>
        <div id="T3L14" class="cell" style="" color=""></div>
        <div id="T3L15" class="cell" style="" color=""></div>
        <div id="T3L16" class="cell" style="" color=""></div>
        <div id="T3L17" class="cell" style="" color=""></div>
        <div id="T3L18" class="cell" style="" color=""></div>
        <div id="T3L19" class="cell" style="" color=""></div>
        <div id="T3L20" class="cell" style="" color=""></div>
        <div id="T3L21" class="cell" style="" color=""></div>
        <div id="T3L22" class="cell" style="" color=""></div>
        <div id="T3L23" class="cell" style="" color=""></div>
        <div id="T3L24" class="cell" style="" color=""></div>
        <div id="T3L25" class="cell" style="" color=""></div>
        <div id="T3L26" class="cell" style="" color=""></div>
        <div id="T3L27" class="cell" style="" color=""></div>
        <div id="T3L28" class="cell" style="" color=""></div>
        <div id="T3L29" class="cell" style="" color=""></div>
        <div id="T3L30" class="cell" style="" color=""></div>
        <div id="T3L31" class="cell" style="" color=""></div>
        <div id="T4L0" class="cell" style="" color=""></div>
        <div id="T4L1" class="cell" style="" color=""></div>
        <div id="T4L2" class="cell" style="" color=""></div>
        <div id="T4L3" class="cell" style="" color=""></div>
        <div id="T4L4" class="cell" style="" color=""></div>
        <div id="T4L5" class="cell" style="" color=""></div>
        <div id="T4L6" class="cell" style="" color=""></div>
        <div id="T4L7" class="cell" style="" color=""></div>
        <div id="T4L8" class="cell" style="" color=""></div>
        <div id="T4L9" class="cell" style="" color=""></div>
        <div id="T4L10" class="cell" style="" color=""></div>
        <div id="T4L11" class="cell" style="" color=""></div>
        <div id="T4L12" class="cell" style="" color=""></div>
        <div id="T4L13" class="cell" style="" color=""></div>
        <div id="T4L14" class="cell" style="" color=""></div>
        <div id="T4L15" class="cell" style="" color=""></div>
        <div id="T4L16" class="cell" style="" color=""></div>
        <div id="T4L17" class="cell" style="" color=""></div>
        <div id="T4L18" class="cell" style="" color=""></div>
        <div id="T4L19" class="cell" style="" color=""></div>
        <div id="T4L20" class="cell" style="" color=""></div>
        <div id="T4L21" class="cell" style="" color=""></div>
        <div id="T4L22" class="cell" style="" color=""></div>
        <div id="T4L23" class="cell" style="" color=""></div>
        <div id="T4L24" class="cell" style="" color=""></div>
        <div id="T4L25" class="cell" style="" color=""></div>
        <div id="T4L26" class="cell" style="" color=""></div>
        <div id="T4L27" class="cell" style="" color=""></div>
        <div id="T4L28" class="cell" style="" color=""></div>
        <div id="T4L29" class="cell" style="" color=""></div>
        <div id="T4L30" class="cell" style="" color=""></div>
        <div id="T4L31" class="cell" style="" color=""></div>
        <div id="T5L0" class="cell" style="" color=""></div>
        <div id="T5L1" class="cell" style="" color=""></div>
        <div id="T5L2" class="cell" style="" color=""></div>
        <div id="T5L3" class="cell" style="" color=""></div>
        <div id="T5L4" class="cell" style="" color=""></div>
        <div id="T5L5" class="cell" style="" color=""></div>
        <div id="T5L6" class="cell" style="" color=""></div>
        <div id="T5L7" class="cell" style="" color=""></div>
        <div id="T5L8" class="cell" style="" color=""></div>
        <div id="T5L9" class="cell" style="" color=""></div>
        <div id="T5L10" class="cell" style="" color=""></div>
        <div id="T5L11" class="cell" style="" color=""></div>
        <div id="T5L12" class="cell" style="" color=""></div>
        <div id="T5L13" class="cell" style="" color=""></div>
        <div id="T5L14" class="cell" style="" color=""></div>
        <div id="T5L15" class="cell" style="" color=""></div>
        <div id="T5L16" class="cell" style="" color=""></div>
        <div id="T5L17" class="cell" style="" color=""></div>
        <div id="T5L18" class="cell" style="" color=""></div>
        <div id="T5L19" class="cell" style="" color=""></div>
        <div id="T5L20" class="cell" style="" color=""></div>
        <div id="T5L21" class="cell" style="" color=""></div>
        <div id="T5L22" class="cell" style="" color=""></div>
        <div id="T5L23" class="cell" style="" color=""></div>
        <div id="T5L24" class="cell" style="" color=""></div>
        <div id="T5L25" class="cell" style="" color=""></div>
        <div id="T5L26" class="cell" style="" color=""></div>
        <div id="T5L27" class="cell" style="" color=""></div>
        <div id="T5L28" class="cell" style="" color=""></div>
        <div id="T5L29" class="cell" style="" color=""></div>
        <div id="T5L30" class="cell" style="" color=""></div>
        <div id="T5L31" class="cell" style="" color=""></div>
        <div id="T6L0" class="cell" style="" color=""></div>
        <div id="T6L1" class="cell" style="" color=""></div>
        <div id="T6L2" class="cell" style="" color=""></div>
        <div id="T6L3" class="cell" style="" color=""></div>
        <div id="T6L4" class="cell" style="" color=""></div>
        <div id="T6L5" class="cell" style="" color=""></div>
        <div id="T6L6" class="cell" style="" color=""></div>
        <div id="T6L7" class="cell" style="" color=""></div>
        <div id="T6L8" class="cell" style="" color=""></div>
        <div id="T6L9" class="cell" style="" color=""></div>
        <div id="T6L10" class="cell" style="" color=""></div>
        <div id="T6L11" class="cell" style="" color=""></div>
        <div id="T6L12" class="cell" style="" color=""></div>
        <div id="T6L13" class="cell" style="" color=""></div>
        <div id="T6L14" class="cell" style="" color=""></div>
        <div id="T6L15" class="cell" style="" color=""></div>
        <div id="T6L16" class="cell" style="" color=""></div>
        <div id="T6L17" class="cell" style="" color=""></div>
        <div id="T6L18" class="cell" style="" color=""></div>
        <div id="T6L19" class="cell" style="" color=""></div>
        <div id="T6L20" class="cell" style="" color=""></div>
        <div id="T6L21" class="cell" style="" color=""></div>
        <div id="T6L22" class="cell" style="" color=""></div>
        <div id="T6L23" class="cell" style="" color=""></div>
        <div id="T6L24" class="cell" style="" color=""></div>
        <div id="T6L25" class="cell" style="" color=""></div>
        <div id="T6L26" class="cell" style="" color=""></div>
        <div id="T6L27" class="cell" style="" color=""></div>
        <div id="T6L28" class="cell" style="" color=""></div>
        <div id="T6L29" class="cell" style="" color=""></div>
        <div id="T6L30" class="cell" style="" color=""></div>
        <div id="T6L31" class="cell" style="" color=""></div>
        <div id="T7L0" class="cell" style="" color=""></div>
        <div id="T7L1" class="cell" style="" color=""></div>
        <div id="T7L2" class="cell" style="" color=""></div>
        <div id="T7L3" class="cell" style="" color=""></div>
        <div id="T7L4" class="cell" style="" color=""></div>
        <div id="T7L5" class="cell" style="" color=""></div>
        <div id="T7L6" class="cell" style="" color=""></div>
        <div id="T7L7" class="cell" style="" color=""></div>
        <div id="T7L8" class="cell" style="" color=""></div>
        <div id="T7L9" class="cell" style="" color=""></div>
        <div id="T7L10" class="cell" style="" color=""></div>
        <div id="T7L11" class="cell" style="" color=""></div>
        <div id="T7L12" class="cell" style="" color=""></div>
        <div id="T7L13" class="cell" style="" color=""></div>
        <div id="T7L14" class="cell" style="" color=""></div>
        <div id="T7L15" class="cell" style="" color=""></div>
        <div id="T7L16" class="cell" style="" color=""></div>
        <div id="T7L17" class="cell" style="" color=""></div>
        <div id="T7L18" class="cell" style="" color=""></div>
        <div id="T7L19" class="cell" style="" color=""></div>
        <div id="T7L20" class="cell" style="" color=""></div>
        <div id="T7L21" class="cell" style="" color=""></div>
        <div id="T7L22" class="cell" style="" color=""></div>
        <div id="T7L23" class="cell" style="" color=""></div>
        <div id="T7L24" class="cell" style="" color=""></div>
        <div id="T7L25" class="cell" style="" color=""></div>
        <div id="T7L26" class="cell" style="" color=""></div>
        <div id="T7L27" class="cell" style="" color=""></div>
        <div id="T7L28" class="cell" style="" color=""></div>
        <div id="T7L29" class="cell" style="" color=""></div>
        <div id="T7L30" class="cell" style="" color=""></div>
        <div id="T7L31" class="cell" style="" color=""></div>
        <div id="T8L0" class="cell" style="" color=""></div>
        <div id="T8L1" class="cell" style="" color=""></div>
        <div id="T8L2" class="cell" style="" color=""></div>
        <div id="T8L3" class="cell" style="" color=""></div>
        <div id="T8L4" class="cell" style="" color=""></div>
        <div id="T8L5" class="cell" style="" color=""></div>
        <div id="T8L6" class="cell" style="" color=""></div>
        <div id="T8L7" class="cell" style="" color=""></div>
        <div id="T8L8" class="cell" style="" color=""></div>
        <div id="T8L9" class="cell" style="" color=""></div>
        <div id="T8L10" class="cell" style="" color=""></div>
        <div id="T8L11" class="cell" style="" color=""></div>
        <div id="T8L12" class="cell" style="" color=""></div>
        <div id="T8L13" class="cell" style="" color=""></div>
        <div id="T8L14" class="cell" style="" color=""></div>
        <div id="T8L15" class="cell" style="" color=""></div>
        <div id="T8L16" class="cell" style="" color=""></div>
        <div id="T8L17" class="cell" style="" color=""></div>
        <div id="T8L18" class="cell" style="" color=""></div>
        <div id="T8L19" class="cell" style="" color=""></div>
        <div id="T8L20" class="cell" style="" color=""></div>
        <div id="T8L21" class="cell" style="" color=""></div>
        <div id="T8L22" class="cell" style="" color=""></div>
        <div id="T8L23" class="cell" style="" color=""></div>
        <div id="T8L24" class="cell" style="" color=""></div>
        <div id="T8L25" class="cell" style="" color=""></div>
        <div id="T8L26" class="cell" style="" color=""></div>
        <div id="T8L27" class="cell" style="" color=""></div>
        <div id="T8L28" class="cell" style="" color=""></div>
        <div id="T8L29" class="cell" style="" color=""></div>
        <div id="T8L30" class="cell" style="" color=""></div>
        <div id="T8L31" class="cell" style="" color=""></div>
        <div id="T9L0" class="cell" style="" color=""></div>
        <div id="T9L1" class="cell" style="" color=""></div>
        <div id="T9L2" class="cell" style="" color=""></div>
        <div id="T9L3" class="cell" style="" color=""></div>
        <div id="T9L4" class="cell" style="" color=""></div>
        <div id="T9L5" class="cell" style="" color=""></div>
        <div id="T9L6" class="cell" style="" color=""></div>
        <div id="T9L7" class="cell" style="" color=""></div>
        <div id="T9L8" class="cell" style="" color=""></div>
        <div id="T9L9" class="cell" style="" color=""></div>
        <div id="T9L10" class="cell" style="" color=""></div>
        <div id="T9L11" class="cell" style="" color=""></div>
        <div id="T9L12" class="cell" style="" color=""></div>
        <div id="T9L13" class="cell" style="" color=""></div>
        <div id="T9L14" class="cell" style="" color=""></div>
        <div id="T9L15" class="cell" style="" color=""></div>
        <div id="T9L16" class="cell" style="" color=""></div>
        <div id="T9L17" class="cell" style="" color=""></div>
        <div id="T9L18" class="cell" style="" color=""></div>
        <div id="T9L19" class="cell" style="" color=""></div>
        <div id="T9L20" class="cell" style="" color=""></div>
        <div id="T9L21" class="cell" style="" color=""></div>
        <div id="T9L22" class="cell" style="" color=""></div>
        <div id="T9L23" class="cell" style="" color=""></div>
        <div id="T9L24" class="cell" style="" color=""></div>
        <div id="T9L25" class="cell" style="" color=""></div>
        <div id="T9L26" class="cell" style="" color=""></div>
        <div id="T9L27" class="cell" style="" color=""></div>
        <div id="T9L28" class="cell" style="" color=""></div>
        <div id="T9L29" class="cell" style="" color=""></div>
        <div id="T9L30" class="cell" style="" color=""></div>
        <div id="T9L31" class="cell" style="" color=""></div>
        <div id="T10L0" class="cell" style="" color=""></div>
        <div id="T10L1" class="cell" style="" color=""></div>
        <div id="T10L2" class="cell" style="" color=""></div>
        <div id="T10L3" class="cell" style="" color=""></div>
        <div id="T10L4" class="cell" style="" color=""></div>
        <div id="T10L5" class="cell" style="" color=""></div>
        <div id="T10L6" class="cell" style="" color=""></div>
        <div id="T10L7" class="cell" style="" color=""></div>
        <div id="T10L8" class="cell" style="" color=""></div>
        <div id="T10L9" class="cell" style="" color=""></div>
        <div id="T10L10" class="cell" style="" color=""></div>
        <div id="T10L11" class="cell" style="" color=""></div>
        <div id="T10L12" class="cell" style="" color=""></div>
        <div id="T10L13" class="cell" style="" color=""></div>
        <div id="T10L14" class="cell" style="" color=""></div>
        <div id="T10L15" class="cell" style="" color=""></div>
        <div id="T10L16" class="cell" style="" color=""></div>
        <div id="T10L17" class="cell" style="" color=""></div>
        <div id="T10L18" class="cell" style="" color=""></div>
        <div id="T10L19" class="cell" style="" color=""></div>
        <div id="T10L20" class="cell" style="" color=""></div>
        <div id="T10L21" class="cell" style="" color=""></div>
        <div id="T10L22" class="cell" style="" color=""></div>
        <div id="T10L23" class="cell" style="" color=""></div>
        <div id="T10L24" class="cell" style="" color=""></div>
        <div id="T10L25" class="cell" style="" color=""></div>
        <div id="T10L26" class="cell" style="" color=""></div>
        <div id="T10L27" class="cell" style="" color=""></div>
        <div id="T10L28" class="cell" style="" color=""></div>
        <div id="T10L29" class="cell" style="" color=""></div>
        <div id="T10L30" class="cell" style="" color=""></div>
        <div id="T10L31" class="cell" style="" color=""></div>
        <div id="T11L0" class="cell" style="" color=""></div>
        <div id="T11L1" class="cell" style="" color=""></div>
        <div id="T11L2" class="cell" style="" color=""></div>
        <div id="T11L3" class="cell" style="" color=""></div>
        <div id="T11L4" class="cell" style="" color=""></div>
        <div id="T11L5" class="cell" style="" color=""></div>
        <div id="T11L6" class="cell" style="" color=""></div>
        <div id="T11L7" class="cell" style="" color=""></div>
        <div id="T11L8" class="cell" style="" color=""></div>
        <div id="T11L9" class="cell" style="" color=""></div>
        <div id="T11L10" class="cell" style="" color=""></div>
        <div id="T11L11" class="cell" style="" color=""></div>
        <div id="T11L12" class="cell" style="" color=""></div>
        <div id="T11L13" class="cell" style="" color=""></div>
        <div id="T11L14" class="cell" style="" color=""></div>
        <div id="T11L15" class="cell" style="" color=""></div>
        <div id="T11L16" class="cell" style="" color=""></div>
        <div id="T11L17" class="cell" style="" color=""></div>
        <div id="T11L18" class="cell" style="" color=""></div>
        <div id="T11L19" class="cell" style="" color=""></div>
        <div id="T11L20" class="cell" style="" color=""></div>
        <div id="T11L21" class="cell" style="" color=""></div>
        <div id="T11L22" class="cell" style="" color=""></div>
        <div id="T11L23" class="cell" style="" color=""></div>
        <div id="T11L24" class="cell" style="" color=""></div>
        <div id="T11L25" class="cell" style="" color=""></div>
        <div id="T11L26" class="cell" style="" color=""></div>
        <div id="T11L27" class="cell" style="" color=""></div>
        <div id="T11L28" class="cell" style="" color=""></div>
        <div id="T11L29" class="cell" style="" color=""></div>
        <div id="T11L30" class="cell" style="" color=""></div>
        <div id="T11L31" class="cell" style="" color=""></div>
        <div id="T12L0" class="cell" style="" color=""></div>
        <div id="T12L1" class="cell" style="" color=""></div>
        <div id="T12L2" class="cell" style="" color=""></div>
        <div id="T12L3" class="cell" style="" color=""></div>
        <div id="T12L4" class="cell" style="" color=""></div>
        <div id="T12L5" class="cell" style="" color=""></div>
        <div id="T12L6" class="cell" style="" color=""></div>
        <div id="T12L7" class="cell" style="" color=""></div>
        <div id="T12L8" class="cell" style="" color=""></div>
        <div id="T12L9" class="cell" style="" color=""></div>
        <div id="T12L10" class="cell" style="" color=""></div>
        <div id="T12L11" class="cell" style="" color=""></div>
        <div id="T12L12" class="cell" style="" color=""></div>
        <div id="T12L13" class="cell" style="" color=""></div>
        <div id="T12L14" class="cell" style="" color=""></div>
        <div id="T12L15" class="cell" style="" color=""></div>
        <div id="T12L16" class="cell" style="" color=""></div>
        <div id="T12L17" class="cell" style="" color=""></div>
        <div id="T12L18" class="cell" style="" color=""></div>
        <div id="T12L19" class="cell" style="" color=""></div>
        <div id="T12L20" class="cell" style="" color=""></div>
        <div id="T12L21" class="cell" style="" color=""></div>
        <div id="T12L22" class="cell" style="" color=""></div>
        <div id="T12L23" class="cell" style="" color=""></div>
        <div id="T12L24" class="cell" style="" color=""></div>
        <div id="T12L25" class="cell" style="" color=""></div>
        <div id="T12L26" class="cell" style="" color=""></div>
        <div id="T12L27" class="cell" style="" color=""></div>
        <div id="T12L28" class="cell" style="" color=""></div>
        <div id="T12L29" class="cell" style="" color=""></div>
        <div id="T12L30" class="cell" style="" color=""></div>
        <div id="T12L31" class="cell" style="" color=""></div>
        <div id="T13L0" class="cell" style="" color=""></div>
        <div id="T13L1" class="cell" style="" color=""></div>
        <div id="T13L2" class="cell" style="" color=""></div>
        <div id="T13L3" class="cell" style="" color=""></div>
        <div id="T13L4" class="cell" style="" color=""></div>
        <div id="T13L5" class="cell" style="" color=""></div>
        <div id="T13L6" class="cell" style="" color=""></div>
        <div id="T13L7" class="cell" style="" color=""></div>
        <div id="T13L8" class="cell" style="" color=""></div>
        <div id="T13L9" class="cell" style="" color=""></div>
        <div id="T13L10" class="cell" style="" color=""></div>
        <div id="T13L11" class="cell" style="" color=""></div>
        <div id="T13L12" class="cell" style="" color=""></div>
        <div id="T13L13" class="cell" style="" color=""></div>
        <div id="T13L14" class="cell" style="" color=""></div>
        <div id="T13L15" class="cell" style="" color=""></div>
        <div id="T13L16" class="cell" style="" color=""></div>
        <div id="T13L17" class="cell" style="" color=""></div>
        <div id="T13L18" class="cell" style="" color=""></div>
        <div id="T13L19" class="cell" style="" color=""></div>
        <div id="T13L20" class="cell" style="" color=""></div>
        <div id="T13L21" class="cell" style="" color=""></div>
        <div id="T13L22" class="cell" style="" color=""></div>
        <div id="T13L23" class="cell" style="" color=""></div>
        <div id="T13L24" class="cell" style="" color=""></div>
        <div id="T13L25" class="cell" style="" color=""></div>
        <div id="T13L26" class="cell" style="" color=""></div>
        <div id="T13L27" class="cell" style="" color=""></div>
        <div id="T13L28" class="cell" style="" color=""></div>
        <div id="T13L29" class="cell" style="" color=""></div>
        <div id="T13L30" class="cell" style="" color=""></div>
        <div id="T13L31" class="cell" style="" color=""></div>
        <div id="T14L0" class="cell" style="" color=""></div>
        <div id="T14L1" class="cell" style="" color=""></div>
        <div id="T14L2" class="cell" style="" color=""></div>
        <div id="T14L3" class="cell" style="" color=""></div>
        <div id="T14L4" class="cell" style="" color=""></div>
        <div id="T14L5" class="cell" style="" color=""></div>
        <div id="T14L6" class="cell" style="" color=""></div>
        <div id="T14L7" class="cell" style="" color=""></div>
        <div id="T14L8" class="cell" style="" color=""></div>
        <div id="T14L9" class="cell" style="" color=""></div>
        <div id="T14L10" class="cell" style="" color=""></div>
        <div id="T14L11" class="cell" style="" color=""></div>
        <div id="T14L12" class="cell" style="" color=""></div>
        <div id="T14L13" class="cell" style="" color=""></div>
        <div id="T14L14" class="cell" style="" color=""></div>
        <div id="T14L15" class="cell" style="" color=""></div>
        <div id="T14L16" class="cell" style="" color=""></div>
        <div id="T14L17" class="cell" style="" color=""></div>
        <div id="T14L18" class="cell" style="" color=""></div>
        <div id="T14L19" class="cell" style="" color=""></div>
        <div id="T14L20" class="cell" style="" color=""></div>
        <div id="T14L21" class="cell" style="" color=""></div>
        <div id="T14L22" class="cell" style="" color=""></div>
        <div id="T14L23" class="cell" style="" color=""></div>
        <div id="T14L24" class="cell" style="" color=""></div>
        <div id="T14L25" class="cell" style="" color=""></div>
        <div id="T14L26" class="cell" style="" color=""></div>
        <div id="T14L27" class="cell" style="" color=""></div>
        <div id="T14L28" class="cell" style="" color=""></div>
        <div id="T14L29" class="cell" style="" color=""></div>
        <div id="T14L30" class="cell" style="" color=""></div>
        <div id="T14L31" class="cell" style="" color=""></div>
        <div id="T15L0" class="cell" style="" color=""></div>
        <div id="T15L1" class="cell" style="" color=""></div>
        <div id="T15L2" class="cell" style="" color=""></div>
        <div id="T15L3" class="cell" style="" color=""></div>
        <div id="T15L4" class="cell" style="" color=""></div>
        <div id="T15L5" class="cell" style="" color=""></div>
        <div id="T15L6" class="cell" style="" color=""></div>
        <div id="T15L7" class="cell" style="" color=""></div>
        <div id="T15L8" class="cell" style="" color=""></div>
        <div id="T15L9" class="cell" style="" color=""></div>
        <div id="T15L10" class="cell" style="" color=""></div>
        <div id="T15L11" class="cell" style="" color=""></div>
        <div id="T15L12" class="cell" style="" color=""></div>
        <div id="T15L13" class="cell" style="" color=""></div>
        <div id="T15L14" class="cell" style="" color=""></div>
        <div id="T15L15" class="cell" style="" color=""></div>
        <div id="T15L16" class="cell" style="" color=""></div>
        <div id="T15L17" class="cell" style="" color=""></div>
        <div id="T15L18" class="cell" style="" color=""></div>
        <div id="T15L19" class="cell" style="" color=""></div>
        <div id="T15L20" class="cell" style="" color=""></div>
        <div id="T15L21" class="cell" style="" color=""></div>
        <div id="T15L22" class="cell" style="" color=""></div>
        <div id="T15L23" class="cell" style="" color=""></div>
        <div id="T15L24" class="cell" style="" color=""></div>
        <div id="T15L25" class="cell" style="" color=""></div>
        <div id="T15L26" class="cell" style="" color=""></div>
        <div id="T15L27" class="cell" style="" color=""></div>
        <div id="T15L28" class="cell" style="" color=""></div>
        <div id="T15L29" class="cell" style="" color=""></div>
        <div id="T15L30" class="cell" style="" color=""></div>
        <div id="T15L31" class="cell" style="" color=""></div>
        <div id="T16L0" class="cell" style="" color=""></div>
        <div id="T16L1" class="cell" style="" color=""></div>
        <div id="T16L2" class="cell" style="" color=""></div>
        <div id="T16L3" class="cell" style="" color=""></div>
        <div id="T16L4" class="cell" style="" color=""></div>
        <div id="T16L5" class="cell" style="" color=""></div>
        <div id="T16L6" class="cell" style="" color=""></div>
        <div id="T16L7" class="cell" style="" color=""></div>
        <div id="T16L8" class="cell" style="" color=""></div>
        <div id="T16L9" class="cell" style="" color=""></div>
        <div id="T16L10" class="cell" style="" color=""></div>
        <div id="T16L11" class="cell" style="" color=""></div>
        <div id="T16L12" class="cell" style="" color=""></div>
        <div id="T16L13" class="cell" style="" color=""></div>
        <div id="T16L14" class="cell" style="" color=""></div>
        <div id="T16L15" class="cell" style="" color=""></div>
        <div id="T16L16" class="cell" style="" color=""></div>
        <div id="T16L17" class="cell" style="" color=""></div>
        <div id="T16L18" class="cell" style="" color=""></div>
        <div id="T16L19" class="cell" style="" color=""></div>
        <div id="T16L20" class="cell" style="" color=""></div>
        <div id="T16L21" class="cell" style="" color=""></div>
        <div id="T16L22" class="cell" style="" color=""></div>
        <div id="T16L23" class="cell" style="" color=""></div>
        <div id="T16L24" class="cell" style="" color=""></div>
        <div id="T16L25" class="cell" style="" color=""></div>
        <div id="T16L26" class="cell" style="" color=""></div>
        <div id="T16L27" class="cell" style="" color=""></div>
        <div id="T16L28" class="cell" style="" color=""></div>
        <div id="T16L29" class="cell" style="" color=""></div>
        <div id="T16L30" class="cell" style="" color=""></div>
        <div id="T16L31" class="cell" style="" color=""></div>
        <div id="T17L0" class="cell" style="" color=""></div>
        <div id="T17L1" class="cell" style="" color=""></div>
        <div id="T17L2" class="cell" style="" color=""></div>
        <div id="T17L3" class="cell" style="" color=""></div>
        <div id="T17L4" class="cell" style="" color=""></div>
        <div id="T17L5" class="cell" style="" color=""></div>
        <div id="T17L6" class="cell" style="" color=""></div>
        <div id="T17L7" class="cell" style="" color=""></div>
        <div id="T17L8" class="cell" style="" color=""></div>
        <div id="T17L9" class="cell" style="" color=""></div>
        <div id="T17L10" class="cell" style="" color=""></div>
        <div id="T17L11" class="cell" style="" color=""></div>
        <div id="T17L12" class="cell" style="" color=""></div>
        <div id="T17L13" class="cell" style="" color=""></div>
        <div id="T17L14" class="cell" style="" color=""></div>
        <div id="T17L15" class="cell" style="" color=""></div>
        <div id="T17L16" class="cell" style="" color=""></div>
        <div id="T17L17" class="cell" style="" color=""></div>
        <div id="T17L18" class="cell" style="" color=""></div>
        <div id="T17L19" class="cell" style="" color=""></div>
        <div id="T17L20" class="cell" style="" color=""></div>
        <div id="T17L21" class="cell" style="" color=""></div>
        <div id="T17L22" class="cell" style="" color=""></div>
        <div id="T17L23" class="cell" style="" color=""></div>
        <div id="T17L24" class="cell" style="" color=""></div>
        <div id="T17L25" class="cell" style="" color=""></div>
        <div id="T17L26" class="cell" style="" color=""></div>
        <div id="T17L27" class="cell" style="" color=""></div>
        <div id="T17L28" class="cell" style="" color=""></div>
        <div id="T17L29" class="cell" style="" color=""></div>
        <div id="T17L30" class="cell" style="" color=""></div>
        <div id="T17L31" class="cell" style="" color=""></div>
        <div id="T18L0" class="cell" style="" color=""></div>
        <div id="T18L1" class="cell" style="" color=""></div>
        <div id="T18L2" class="cell" style="" color=""></div>
        <div id="T18L3" class="cell" style="" color=""></div>
        <div id="T18L4" class="cell" style="" color=""></div>
        <div id="T18L5" class="cell" style="" color=""></div>
        <div id="T18L6" class="cell" style="" color=""></div>
        <div id="T18L7" class="cell" style="" color=""></div>
        <div id="T18L8" class="cell" style="" color=""></div>
        <div id="T18L9" class="cell" style="" color=""></div>
        <div id="T18L10" class="cell" style="" color=""></div>
        <div id="T18L11" class="cell" style="" color=""></div>
        <div id="T18L12" class="cell" style="" color=""></div>
        <div id="T18L13" class="cell" style="" color=""></div>
        <div id="T18L14" class="cell" style="" color=""></div>
        <div id="T18L15" class="cell" style="" color=""></div>
        <div id="T18L16" class="cell" style="" color=""></div>
        <div id="T18L17" class="cell" style="" color=""></div>
        <div id="T18L18" class="cell" style="" color=""></div>
        <div id="T18L19" class="cell" style="" color=""></div>
        <div id="T18L20" class="cell" style="" color=""></div>
        <div id="T18L21" class="cell" style="" color=""></div>
        <div id="T18L22" class="cell" style="" color=""></div>
        <div id="T18L23" class="cell" style="" color=""></div>
        <div id="T18L24" class="cell" style="" color=""></div>
        <div id="T18L25" class="cell" style="" color=""></div>
        <div id="T18L26" class="cell" style="" color=""></div>
        <div id="T18L27" class="cell" style="" color=""></div>
        <div id="T18L28" class="cell" style="" color=""></div>
        <div id="T18L29" class="cell" style="" color=""></div>
        <div id="T18L30" class="cell" style="" color=""></div>
        <div id="T18L31" class="cell" style="" color=""></div>
        <div id="T19L0" class="cell" style="" color=""></div>
        <div id="T19L1" class="cell" style="" color=""></div>
        <div id="T19L2" class="cell" style="" color=""></div>
        <div id="T19L3" class="cell" style="" color=""></div>
        <div id="T19L4" class="cell" style="" color=""></div>
        <div id="T19L5" class="cell" style="" color=""></div>
        <div id="T19L6" class="cell" style="" color=""></div>
        <div id="T19L7" class="cell" style="" color=""></div>
        <div id="T19L8" class="cell" style="" color=""></div>
        <div id="T19L9" class="cell" style="" color=""></div>
        <div id="T19L10" class="cell" style="" color=""></div>
        <div id="T19L11" class="cell" style="" color=""></div>
        <div id="T19L12" class="cell" style="" color=""></div>
        <div id="T19L13" class="cell" style="" color=""></div>
        <div id="T19L14" class="cell" style="" color=""></div>
        <div id="T19L15" class="cell" style="" color=""></div>
        <div id="T19L16" class="cell" style="" color=""></div>
        <div id="T19L17" class="cell" style="" color=""></div>
        <div id="T19L18" class="cell" style="" color=""></div>
        <div id="T19L19" class="cell" style="" color=""></div>
        <div id="T19L20" class="cell" style="" color=""></div>
        <div id="T19L21" class="cell" style="" color=""></div>
        <div id="T19L22" class="cell" style="" color=""></div>
        <div id="T19L23" class="cell" style="" color=""></div>
        <div id="T19L24" class="cell" style="" color=""></div>
        <div id="T19L25" class="cell" style="" color=""></div>
        <div id="T19L26" class="cell" style="" color=""></div>
        <div id="T19L27" class="cell" style="" color=""></div>
        <div id="T19L28" class="cell" style="" color=""></div>
        <div id="T19L29" class="cell" style="" color=""></div>
        <div id="T19L30" class="cell" style="" color=""></div>
        <div id="T19L31" class="cell" style="" color=""></div>
        <div id="T20L0" class="cell" style="" color=""></div>
        <div id="T20L1" class="cell" style="" color=""></div>
        <div id="T20L2" class="cell" style="" color=""></div>
        <div id="T20L3" class="cell" style="" color=""></div>
        <div id="T20L4" class="cell" style="" color=""></div>
        <div id="T20L5" class="cell" style="" color=""></div>
        <div id="T20L6" class="cell" style="" color=""></div>
        <div id="T20L7" class="cell" style="" color=""></div>
        <div id="T20L8" class="cell" style="" color=""></div>
        <div id="T20L9" class="cell" style="" color=""></div>
        <div id="T20L10" class="cell" style="" color=""></div>
        <div id="T20L11" class="cell" style="" color=""></div>
        <div id="T20L12" class="cell" style="" color=""></div>
        <div id="T20L13" class="cell" style="" color=""></div>
        <div id="T20L14" class="cell" style="" color=""></div>
        <div id="T20L15" class="cell" style="" color=""></div>
        <div id="T20L16" class="cell" style="" color=""></div>
        <div id="T20L17" class="cell" style="" color=""></div>
        <div id="T20L18" class="cell" style="" color=""></div>
        <div id="T20L19" class="cell" style="" color=""></div>
        <div id="T20L20" class="cell" style="" color=""></div>
        <div id="T20L21" class="cell" style="" color=""></div>
        <div id="T20L22" class="cell" style="" color=""></div>
        <div id="T20L23" class="cell" style="" color=""></div>
        <div id="T20L24" class="cell" style="" color=""></div>
        <div id="T20L25" class="cell" style="" color=""></div>
        <div id="T20L26" class="cell" style="" color=""></div>
        <div id="T20L27" class="cell" style="" color=""></div>
        <div id="T20L28" class="cell" style="" color=""></div>
        <div id="T20L29" class="cell" style="" color=""></div>
        <div id="T20L30" class="cell" style="" color=""></div>
        <div id="T20L31" class="cell" style="" color=""></div>
        <div id="T21L0" class="cell" style="" color=""></div>
        <div id="T21L1" class="cell" style="" color=""></div>
        <div id="T21L2" class="cell" style="" color=""></div>
        <div id="T21L3" class="cell" style="" color=""></div>
        <div id="T21L4" class="cell" style="" color=""></div>
        <div id="T21L5" class="cell" style="" color=""></div>
        <div id="T21L6" class="cell" style="" color=""></div>
        <div id="T21L7" class="cell" style="" color=""></div>
        <div id="T21L8" class="cell" style="" color=""></div>
        <div id="T21L9" class="cell" style="" color=""></div>
        <div id="T21L10" class="cell" style="" color=""></div>
        <div id="T21L11" class="cell" style="" color=""></div>
        <div id="T21L12" class="cell" style="" color=""></div>
        <div id="T21L13" class="cell" style="" color=""></div>
        <div id="T21L14" class="cell" style="" color=""></div>
        <div id="T21L15" class="cell" style="" color=""></div>
        <div id="T21L16" class="cell" style="" color=""></div>
        <div id="T21L17" class="cell" style="" color=""></div>
        <div id="T21L18" class="cell" style="" color=""></div>
        <div id="T21L19" class="cell" style="" color=""></div>
        <div id="T21L20" class="cell" style="" color=""></div>
        <div id="T21L21" class="cell" style="" color=""></div>
        <div id="T21L22" class="cell" style="" color=""></div>
        <div id="T21L23" class="cell" style="" color=""></div>
        <div id="T21L24" class="cell" style="" color=""></div>
        <div id="T21L25" class="cell" style="" color=""></div>
        <div id="T21L26" class="cell" style="" color=""></div>
        <div id="T21L27" class="cell" style="" color=""></div>
        <div id="T21L28" class="cell" style="" color=""></div>
        <div id="T21L29" class="cell" style="" color=""></div>
        <div id="T21L30" class="cell" style="" color=""></div>
        <div id="T21L31" class="cell" style="" color=""></div>
        <div id="T22L0" class="cell" style="" color=""></div>
        <div id="T22L1" class="cell" style="" color=""></div>
        <div id="T22L2" class="cell" style="" color=""></div>
        <div id="T22L3" class="cell" style="" color=""></div>
        <div id="T22L4" class="cell" style="" color=""></div>
        <div id="T22L5" class="cell" style="" color=""></div>
        <div id="T22L6" class="cell" style="" color=""></div>
        <div id="T22L7" class="cell" style="" color=""></div>
        <div id="T22L8" class="cell" style="" color=""></div>
        <div id="T22L9" class="cell" style="" color=""></div>
        <div id="T22L10" class="cell" style="" color=""></div>
        <div id="T22L11" class="cell" style="" color=""></div>
        <div id="T22L12" class="cell" style="" color=""></div>
        <div id="T22L13" class="cell" style="" color=""></div>
        <div id="T22L14" class="cell" style="" color=""></div>
        <div id="T22L15" class="cell" style="" color=""></div>
        <div id="T22L16" class="cell" style="" color=""></div>
        <div id="T22L17" class="cell" style="" color=""></div>
        <div id="T22L18" class="cell" style="" color=""></div>
        <div id="T22L19" class="cell" style="" color=""></div>
        <div id="T22L20" class="cell" style="" color=""></div>
        <div id="T22L21" class="cell" style="" color=""></div>
        <div id="T22L22" class="cell" style="" color=""></div>
        <div id="T22L23" class="cell" style="" color=""></div>
        <div id="T22L24" class="cell" style="" color=""></div>
        <div id="T22L25" class="cell" style="" color=""></div>
        <div id="T22L26" class="cell" style="" color=""></div>
        <div id="T22L27" class="cell" style="" color=""></div>
        <div id="T22L28" class="cell" style="" color=""></div>
        <div id="T22L29" class="cell" style="" color=""></div>
        <div id="T22L30" class="cell" style="" color=""></div>
        <div id="T22L31" class="cell" style="" color=""></div>
        <div id="T23L0" class="cell" style="" color=""></div>
        <div id="T23L1" class="cell" style="" color=""></div>
        <div id="T23L2" class="cell" style="" color=""></div>
        <div id="T23L3" class="cell" style="" color=""></div>
        <div id="T23L4" class="cell" style="" color=""></div>
        <div id="T23L5" class="cell" style="" color=""></div>
        <div id="T23L6" class="cell" style="" color=""></div>
        <div id="T23L7" class="cell" style="" color=""></div>
        <div id="T23L8" class="cell" style="" color=""></div>
        <div id="T23L9" class="cell" style="" color=""></div>
        <div id="T23L10" class="cell" style="" color=""></div>
        <div id="T23L11" class="cell" style="" color=""></div>
        <div id="T23L12" class="cell" style="" color=""></div>
        <div id="T23L13" class="cell" style="" color=""></div>
        <div id="T23L14" class="cell" style="" color=""></div>
        <div id="T23L15" class="cell" style="" color=""></div>
        <div id="T23L16" class="cell" style="" color=""></div>
        <div id="T23L17" class="cell" style="" color=""></div>
        <div id="T23L18" class="cell" style="" color=""></div>
        <div id="T23L19" class="cell" style="" color=""></div>
        <div id="T23L20" class="cell" style="" color=""></div>
        <div id="T23L21" class="cell" style="" color=""></div>
        <div id="T23L22" class="cell" style="" color=""></div>
        <div id="T23L23" class="cell" style="" color=""></div>
        <div id="T23L24" class="cell" style="" color=""></div>
        <div id="T23L25" class="cell" style="" color=""></div>
        <div id="T23L26" class="cell" style="" color=""></div>
        <div id="T23L27" class="cell" style="" color=""></div>
        <div id="T23L28" class="cell" style="" color=""></div>
        <div id="T23L29" class="cell" style="" color=""></div>
        <div id="T23L30" class="cell" style="" color=""></div>
        <div id="T23L31" class="cell" style="" color=""></div>
        <div id="T24L0" class="cell" style="" color=""></div>
        <div id="T24L1" class="cell" style="" color=""></div>
        <div id="T24L2" class="cell" style="" color=""></div>
        <div id="T24L3" class="cell" style="" color=""></div>
        <div id="T24L4" class="cell" style="" color=""></div>
        <div id="T24L5" class="cell" style="" color=""></div>
        <div id="T24L6" class="cell" style="" color=""></div>
        <div id="T24L7" class="cell" style="" color=""></div>
        <div id="T24L8" class="cell" style="" color=""></div>
        <div id="T24L9" class="cell" style="" color=""></div>
        <div id="T24L10" class="cell" style="" color=""></div>
        <div id="T24L11" class="cell" style="" color=""></div>
        <div id="T24L12" class="cell" style="" color=""></div>
        <div id="T24L13" class="cell" style="" color=""></div>
        <div id="T24L14" class="cell" style="" color=""></div>
        <div id="T24L15" class="cell" style="" color=""></div>
        <div id="T24L16" class="cell" style="" color=""></div>
        <div id="T24L17" class="cell" style="" color=""></div>
        <div id="T24L18" class="cell" style="" color=""></div>
        <div id="T24L19" class="cell" style="" color=""></div>
        <div id="T24L20" class="cell" style="" color=""></div>
        <div id="T24L21" class="cell" style="" color=""></div>
        <div id="T24L22" class="cell" style="" color=""></div>
        <div id="T24L23" class="cell" style="" color=""></div>
        <div id="T24L24" class="cell" style="" color=""></div>
        <div id="T24L25" class="cell" style="" color=""></div>
        <div id="T24L26" class="cell" style="" color=""></div>
        <div id="T24L27" class="cell" style="" color=""></div>
        <div id="T24L28" class="cell" style="" color=""></div>
        <div id="T24L29" class="cell" style="" color=""></div>
        <div id="T24L30" class="cell" style="" color=""></div>
        <div id="T24L31" class="cell" style="" color=""></div>
        <div id="T25L0" class="cell" style="" color=""></div>
        <div id="T25L1" class="cell" style="" color=""></div>
        <div id="T25L2" class="cell" style="" color=""></div>
        <div id="T25L3" class="cell" style="" color=""></div>
        <div id="T25L4" class="cell" style="" color=""></div>
        <div id="T25L5" class="cell" style="" color=""></div>
        <div id="T25L6" class="cell" style="" color=""></div>
        <div id="T25L7" class="cell" style="" color=""></div>
        <div id="T25L8" class="cell" style="" color=""></div>
        <div id="T25L9" class="cell" style="" color=""></div>
        <div id="T25L10" class="cell" style="" color=""></div>
        <div id="T25L11" class="cell" style="" color=""></div>
        <div id="T25L12" class="cell" style="" color=""></div>
        <div id="T25L13" class="cell" style="" color=""></div>
        <div id="T25L14" class="cell" style="" color=""></div>
        <div id="T25L15" class="cell" style="" color=""></div>
        <div id="T25L16" class="cell" style="" color=""></div>
        <div id="T25L17" class="cell" style="" color=""></div>
        <div id="T25L18" class="cell" style="" color=""></div>
        <div id="T25L19" class="cell" style="" color=""></div>
        <div id="T25L20" class="cell" style="" color=""></div>
        <div id="T25L21" class="cell" style="" color=""></div>
        <div id="T25L22" class="cell" style="" color=""></div>
        <div id="T25L23" class="cell" style="" color=""></div>
        <div id="T25L24" class="cell" style="" color=""></div>
        <div id="T25L25" class="cell" style="" color=""></div>
        <div id="T25L26" class="cell" style="" color=""></div>
        <div id="T25L27" class="cell" style="" color=""></div>
        <div id="T25L28" class="cell" style="" color=""></div>
        <div id="T25L29" class="cell" style="" color=""></div>
        <div id="T25L30" class="cell" style="" color=""></div>
        <div id="T25L31" class="cell" style="" color=""></div>
        <div id="T26L0" class="cell" style="" color=""></div>
        <div id="T26L1" class="cell" style="" color=""></div>
        <div id="T26L2" class="cell" style="" color=""></div>
        <div id="T26L3" class="cell" style="" color=""></div>
        <div id="T26L4" class="cell" style="" color=""></div>
        <div id="T26L5" class="cell" style="" color=""></div>
        <div id="T26L6" class="cell" style="" color=""></div>
        <div id="T26L7" class="cell" style="" color=""></div>
        <div id="T26L8" class="cell" style="" color=""></div>
        <div id="T26L9" class="cell" style="" color=""></div>
        <div id="T26L10" class="cell" style="" color=""></div>
        <div id="T26L11" class="cell" style="" color=""></div>
        <div id="T26L12" class="cell" style="" color=""></div>
        <div id="T26L13" class="cell" style="" color=""></div>
        <div id="T26L14" class="cell" style="" color=""></div>
        <div id="T26L15" class="cell" style="" color=""></div>
        <div id="T26L16" class="cell" style="" color=""></div>
        <div id="T26L17" class="cell" style="" color=""></div>
        <div id="T26L18" class="cell" style="" color=""></div>
        <div id="T26L19" class="cell" style="" color=""></div>
        <div id="T26L20" class="cell" style="" color=""></div>
        <div id="T26L21" class="cell" style="" color=""></div>
        <div id="T26L22" class="cell" style="" color=""></div>
        <div id="T26L23" class="cell" style="" color=""></div>
        <div id="T26L24" class="cell" style="" color=""></div>
        <div id="T26L25" class="cell" style="" color=""></div>
        <div id="T26L26" class="cell" style="" color=""></div>
        <div id="T26L27" class="cell" style="" color=""></div>
        <div id="T26L28" class="cell" style="" color=""></div>
        <div id="T26L29" class="cell" style="" color=""></div>
        <div id="T26L30" class="cell" style="" color=""></div>
        <div id="T26L31" class="cell" style="" color=""></div>
        <div id="T27L0" class="cell" style="" color=""></div>
        <div id="T27L1" class="cell" style="" color=""></div>
        <div id="T27L2" class="cell" style="" color=""></div>
        <div id="T27L3" class="cell" style="" color=""></div>
        <div id="T27L4" class="cell" style="" color=""></div>
        <div id="T27L5" class="cell" style="" color=""></div>
        <div id="T27L6" class="cell" style="" color=""></div>
        <div id="T27L7" class="cell" style="" color=""></div>
        <div id="T27L8" class="cell" style="" color=""></div>
        <div id="T27L9" class="cell" style="" color=""></div>
        <div id="T27L10" class="cell" style="" color=""></div>
        <div id="T27L11" class="cell" style="" color=""></div>
        <div id="T27L12" class="cell" style="" color=""></div>
        <div id="T27L13" class="cell" style="" color=""></div>
        <div id="T27L14" class="cell" style="" color=""></div>
        <div id="T27L15" class="cell" style="" color=""></div>
        <div id="T27L16" class="cell" style="" color=""></div>
        <div id="T27L17" class="cell" style="" color=""></div>
        <div id="T27L18" class="cell" style="" color=""></div>
        <div id="T27L19" class="cell" style="" color=""></div>
        <div id="T27L20" class="cell" style="" color=""></div>
        <div id="T27L21" class="cell" style="" color=""></div>
        <div id="T27L22" class="cell" style="" color=""></div>
        <div id="T27L23" class="cell" style="" color=""></div>
        <div id="T27L24" class="cell" style="" color=""></div>
        <div id="T27L25" class="cell" style="" color=""></div>
        <div id="T27L26" class="cell" style="" color=""></div>
        <div id="T27L27" class="cell" style="" color=""></div>
        <div id="T27L28" class="cell" style="" color=""></div>
        <div id="T27L29" class="cell" style="" color=""></div>
        <div id="T27L30" class="cell" style="" color=""></div>
        <div id="T27L31" class="cell" style="" color=""></div>
        <div id="T28L0" class="cell" style="" color=""></div>
        <div id="T28L1" class="cell" style="" color=""></div>
        <div id="T28L2" class="cell" style="" color=""></div>
        <div id="T28L3" class="cell" style="" color=""></div>
        <div id="T28L4" class="cell" style="" color=""></div>
        <div id="T28L5" class="cell" style="" color=""></div>
        <div id="T28L6" class="cell" style="" color=""></div>
        <div id="T28L7" class="cell" style="" color=""></div>
        <div id="T28L8" class="cell" style="" color=""></div>
        <div id="T28L9" class="cell" style="" color=""></div>
        <div id="T28L10" class="cell" style="" color=""></div>
        <div id="T28L11" class="cell" style="" color=""></div>
        <div id="T28L12" class="cell" style="" color=""></div>
        <div id="T28L13" class="cell" style="" color=""></div>
        <div id="T28L14" class="cell" style="" color=""></div>
        <div id="T28L15" class="cell" style="" color=""></div>
        <div id="T28L16" class="cell" style="" color=""></div>
        <div id="T28L17" class="cell" style="" color=""></div>
        <div id="T28L18" class="cell" style="" color=""></div>
        <div id="T28L19" class="cell" style="" color=""></div>
        <div id="T28L20" class="cell" style="" color=""></div>
        <div id="T28L21" class="cell" style="" color=""></div>
        <div id="T28L22" class="cell" style="" color=""></div>
        <div id="T28L23" class="cell" style="" color=""></div>
        <div id="T28L24" class="cell" style="" color=""></div>
        <div id="T28L25" class="cell" style="" color=""></div>
        <div id="T28L26" class="cell" style="" color=""></div>
        <div id="T28L27" class="cell" style="" color=""></div>
        <div id="T28L28" class="cell" style="" color=""></div>
        <div id="T28L29" class="cell" style="" color=""></div>
        <div id="T28L30" class="cell" style="" color=""></div>
        <div id="T28L31" class="cell" style="" color=""></div>
        <div id="T29L0" class="cell" style="" color=""></div>
        <div id="T29L1" class="cell" style="" color=""></div>
        <div id="T29L2" class="cell" style="" color=""></div>
        <div id="T29L3" class="cell" style="" color=""></div>
        <div id="T29L4" class="cell" style="" color=""></div>
        <div id="T29L5" class="cell" style="" color=""></div>
        <div id="T29L6" class="cell" style="" color=""></div>
        <div id="T29L7" class="cell" style="" color=""></div>
        <div id="T29L8" class="cell" style="" color=""></div>
        <div id="T29L9" class="cell" style="" color=""></div>
        <div id="T29L10" class="cell" style="" color=""></div>
        <div id="T29L11" class="cell" style="" color=""></div>
        <div id="T29L12" class="cell" style="" color=""></div>
        <div id="T29L13" class="cell" style="" color=""></div>
        <div id="T29L14" class="cell" style="" color=""></div>
        <div id="T29L15" class="cell" style="" color=""></div>
        <div id="T29L16" class="cell" style="" color=""></div>
        <div id="T29L17" class="cell" style="" color=""></div>
        <div id="T29L18" class="cell" style="" color=""></div>
        <div id="T29L19" class="cell" style="" color=""></div>
        <div id="T29L20" class="cell" style="" color=""></div>
        <div id="T29L21" class="cell" style="" color=""></div>
        <div id="T29L22" class="cell" style="" color=""></div>
        <div id="T29L23" class="cell" style="" color=""></div>
        <div id="T29L24" class="cell" style="" color=""></div>
        <div id="T29L25" class="cell" style="" color=""></div>
        <div id="T29L26" class="cell" style="" color=""></div>
        <div id="T29L27" class="cell" style="" color=""></div>
        <div id="T29L28" class="cell" style="" color=""></div>
        <div id="T29L29" class="cell" style="" color=""></div>
        <div id="T29L30" class="cell" style="" color=""></div>
        <div id="T29L31" class="cell" style="" color=""></div>
        <div id="T30L0" class="cell" style="" color=""></div>
        <div id="T30L1" class="cell" style="" color=""></div>
        <div id="T30L2" class="cell" style="" color=""></div>
        <div id="T30L3" class="cell" style="" color=""></div>
        <div id="T30L4" class="cell" style="" color=""></div>
        <div id="T30L5" class="cell" style="" color=""></div>
        <div id="T30L6" class="cell" style="" color=""></div>
        <div id="T30L7" class="cell" style="" color=""></div>
        <div id="T30L8" class="cell" style="" color=""></div>
        <div id="T30L9" class="cell" style="" color=""></div>
        <div id="T30L10" class="cell" style="" color=""></div>
        <div id="T30L11" class="cell" style="" color=""></div>
        <div id="T30L12" class="cell" style="" color=""></div>
        <div id="T30L13" class="cell" style="" color=""></div>
        <div id="T30L14" class="cell" style="" color=""></div>
        <div id="T30L15" class="cell" style="" color=""></div>
        <div id="T30L16" class="cell" style="" color=""></div>
        <div id="T30L17" class="cell" style="" color=""></div>
        <div id="T30L18" class="cell" style="" color=""></div>
        <div id="T30L19" class="cell" style="" color=""></div>
        <div id="T30L20" class="cell" style="" color=""></div>
        <div id="T30L21" class="cell" style="" color=""></div>
        <div id="T30L22" class="cell" style="" color=""></div>
        <div id="T30L23" class="cell" style="" color=""></div>
        <div id="T30L24" class="cell" style="" color=""></div>
        <div id="T30L25" class="cell" style="" color=""></div>
        <div id="T30L26" class="cell" style="" color=""></div>
        <div id="T30L27" class="cell" style="" color=""></div>
        <div id="T30L28" class="cell" style="" color=""></div>
        <div id="T30L29" class="cell" style="" color=""></div>
        <div id="T30L30" class="cell" style="" color=""></div>
        <div id="T30L31" class="cell" style="" color=""></div>
        <div id="T31L0" class="cell" style="" color=""></div>
        <div id="T31L1" class="cell" style="" color=""></div>
        <div id="T31L2" class="cell" style="" color=""></div>
        <div id="T31L3" class="cell" style="" color=""></div>
        <div id="T31L4" class="cell" style="" color=""></div>
        <div id="T31L5" class="cell" style="" color=""></div>
        <div id="T31L6" class="cell" style="" color=""></div>
        <div id="T31L7" class="cell" style="" color=""></div>
        <div id="T31L8" class="cell" style="" color=""></div>
        <div id="T31L9" class="cell" style="" color=""></div>
        <div id="T31L10" class="cell" style="" color=""></div>
        <div id="T31L11" class="cell" style="" color=""></div>
        <div id="T31L12" class="cell" style="" color=""></div>
        <div id="T31L13" class="cell" style="" color=""></div>
        <div id="T31L14" class="cell" style="" color=""></div>
        <div id="T31L15" class="cell" style="" color=""></div>
        <div id="T31L16" class="cell" style="" color=""></div>
        <div id="T31L17" class="cell" style="" color=""></div>
        <div id="T31L18" class="cell" style="" color=""></div>
        <div id="T31L19" class="cell" style="" color=""></div>
        <div id="T31L20" class="cell" style="" color=""></div>
        <div id="T31L21" class="cell" style="" color=""></div>
        <div id="T31L22" class="cell" style="" color=""></div>
        <div id="T31L23" class="cell" style="" color=""></div>
        <div id="T31L24" class="cell" style="" color=""></div>
        <div id="T31L25" class="cell" style="" color=""></div>
        <div id="T31L26" class="cell" style="" color=""></div>
        <div id="T31L27" class="cell" style="" color=""></div>
        <div id="T31L28" class="cell" style="" color=""></div>
        <div id="T31L29" class="cell" style="" color=""></div>
        <div id="T31L30" class="cell" style="" color=""></div>
        <div id="T31L31" class="cell" style="" color=""></div>
        <!-- HEADS -->
        <div id="Head0" class="head" hidden="true">
          <div class="eye  eye00"></div>
          <div class="deye eye01" hidden="true"></div>
          <div class="deye eye10" hidden="true"></div>
          <div class="deye eye02" hidden="true"></div>
          <div class="deye eye20" hidden="true"></div>
          <div class="eye  eye11"></div>
        </div>
        <div id="Head1" class="head" hidden="true">
          <div class="eye  eye00"></div>
          <div class="deye eye01" hidden="true"></div>
          <div class="deye eye10" hidden="true"></div>
          <div class="deye eye02" hidden="true"></div>
          <div class="deye eye20" hidden="true"></div>
          <div class="eye  eye11"></div>
        </div>
        <div id="Head2" class="head" hidden="true">
          <div class="eye  eye00"></div>
          <div class="deye eye01" hidden="true"></div>
          <div class="deye eye10" hidden="true"></div>
          <div class="deye eye02" hidden="true"></div>
          <div class="deye eye20" hidden="true"></div>
          <div class="eye  eye11"></div>
        </div>
        <div id="Head3" class="head" hidden="true">
          <div class="eye  eye00"></div>
          <div class="deye eye01" hidden="true"></div>
          <div class="deye eye10" hidden="true"></div>
          <div class="deye eye02" hidden="true"></div>
          <div class="deye eye20" hidden="true"></div>
          <div class="eye  eye11"></div>
        </div>
      </div>
    </div>
  </body>
</html>