CREATE DATABASE IF NOT EXISTS tron;

USE tron;

DROP TABLE IF EXISTS tron;

CREATE TABLE tron (
  GameID                VARCHAR(4)      NOT NULL                    PRIMARY KEY,
  Clock                 INT             NOT NULL                    DEFAULT 0,
  Ready                 INT             NOT NULL                    DEFAULT 0,
  R0_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R1_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R2_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R3_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R4_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R5_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R6_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R7_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R8_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R9_0                  BIGINT          NOT NULL                    DEFAULT 0,
  R10_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R11_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R12_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R13_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R14_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R15_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R16_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R17_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R18_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R19_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R20_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R21_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R22_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R23_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R24_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R25_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R26_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R27_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R28_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R29_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R30_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R31_0                 BIGINT          NOT NULL                    DEFAULT 0,
  R0_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R1_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R2_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R3_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R4_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R5_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R6_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R7_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R8_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R9_1                  BIGINT          NOT NULL                    DEFAULT 0,
  R10_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R11_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R12_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R13_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R14_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R15_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R16_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R17_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R18_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R19_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R20_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R21_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R22_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R23_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R24_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R25_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R26_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R27_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R28_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R29_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R30_1                 BIGINT          NOT NULL                    DEFAULT 0,
  R31_1                 BIGINT          NOT NULL                    DEFAULT 0
);